name: App
on:
  push:
    paths: ['app/**', '.github/workflows/app.yml']
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION:    ${{ secrets.AWS_REGION }}
  ECR_REPO_NAME: case1nca-api
  CLUSTER_NAME:  case1-nca
  SERVICE_NAME:  app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_APP }}
          aws-region:     ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          platforms: linux/amd64
          push: true
          tags: ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:latest

      - name: Force ECS redeploy
        run: |
          aws ecs update-service \
            --cluster "${{ env.CLUSTER_NAME }}" \
            --service "${{ env.SERVICE_NAME }}" \
            --force-new-deployment
