name: Terraform

on:
  workflow_dispatch:
  pull_request:
    paths: ["infra/**"]
  push:
    branches: ["main"]
    paths: ["infra/**"]

jobs:
  tf:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: infra/envs/dev  # voer alle TF-commando's hier uit

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::760981412376:role/GitHubActionsOIDC
          aws-region: eu-central-1

      # Terraform staat nu lokaal geïnstalleerd (choco), dus direct gebruiken
      - name: Terraform version
        shell: powershell
        run: terraform -version

      - name: Terraform fmt (write)
        shell: powershell
        run: terraform fmt -recursive

      - name: Terraform init
        shell: powershell
        env:
          TF_IN_AUTOMATION: "1"
        run: terraform init -upgrade

      - name: Terraform validate
        shell: powershell
        env:
          TF_IN_AUTOMATION: "1"
        run: terraform validate -no-color

      - name: Terraform plan (PR)
        if: github.event_name == 'pull_request'
        shell: powershell
        env:
          TF_IN_AUTOMATION: "1"
        run: terraform plan -out=tfplan

      - name: Terraform apply (main)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        shell: powershell
        env:
          TF_IN_AUTOMATION: "1"
        run: terraform apply -auto-approve
