name: Terraform

on:
  push:
    branches: ["main"]
    paths: ["infra/**", ".github/workflows/terraform.yml"]
  pull_request:
    paths: ["infra/**", ".github/workflows/terraform.yml"]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_IN_AUTOMATION: true

jobs:
  apply-mac:
    name: Apply (macOS self-hosted)
    runs-on: [self-hosted, mac]
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    defaults:
      run:
        shell: bash
        working-directory: infra/envs/dev
    env:
      # Gebruik overal TF_VAR_ → geen -var vlaggen meer nodig
      TF_VAR_db_master_username: appadmin
      TF_VAR_db_master_password: ${{ secrets.DB_MASTER_PASSWORD }}
      TF_VAR_db_password_secret_name: ${{ secrets.TF_VAR_DB_PASSWORD_SECRET_NAME }}
      TF_VAR_vpc_id:     ${{ vars.VPC_ID }}
      TF_VAR_subnet_id:  ${{ vars.SUBNET_ID }}
      TF_VAR_my_ip_cidr: ${{ vars.MY_IP_CIDR }}
      TF_VAR_env:        ${{ vars.ENV }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region:     ${{ env.AWS_REGION }}

      - name: Who am I
        run: aws sts get-caller-identity

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform fmt (non-blocking)
        run: terraform fmt -recursive -check || true

      - name: Terraform init (S3 backend)
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
            -backend-config="key=envs/${{ vars.ENV }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_BACKEND_DYNAMODB_TABLE }}"

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve -lock-timeout=5m

  plan-pr:
    name: Plan (PR)
    runs-on: [self-hosted, mac]
    if: github.event_name == 'pull_request'
    defaults:
      run:
        shell: bash
        working-directory: infra/envs/dev
    env:
      TF_VAR_db_master_username: appadmin
      TF_VAR_db_master_password: ${{ secrets.DB_MASTER_PASSWORD }}
      TF_VAR_db_password_secret_name: ${{ secrets.TF_VAR_DB_PASSWORD_SECRET_NAME }}
      TF_VAR_vpc_id:     ${{ vars.VPC_ID }}
      TF_VAR_subnet_id:  ${{ vars.SUBNET_ID }}
      TF_VAR_my_ip_cidr: ${{ vars.MY_IP_CIDR }}
      TF_VAR_env:        ${{ vars.ENV }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region:     ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform fmt (non-blocking)
        run: terraform fmt -recursive -check || true

      - name: Terraform init (S3 backend)
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
            -backend-config="key=envs/${{ vars.ENV }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_BACKEND_DYNAMODB_TABLE }}"

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan -input=false -no-color -out=tfplan -lock-timeout=5m
