name: Terraform

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Runner for APPLY"
        required: true
        default: windows
        type: choice
        options: [windows, mac]
  push:
    branches: [ "main" ]
    paths: [ "infra/**" ]
  pull_request:
    paths: [ "infra/**" ]

permissions:
  contents: read

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  apply-windows:
    name: Apply (Windows self-hosted)
    runs-on: [self-hosted, windows]
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.target == 'windows'))
    defaults:
      run:
        shell: powershell
        working-directory: infra/envs/dev
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (temporary creds)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init (backend.hcl)
        run: terraform init -input=false -reconfigure -backend-config="backend.hcl"

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        env:
          TF_VAR_db_master_password:  ${{ secrets.TF_VAR_DB_MASTER_PASSWORD }}
          TF_VAR_db_master_username:  ${{ secrets.TF_VAR_DB_MASTER_USERNAME }} # zie noot hieronder
        run: terraform apply -input=false -auto-approve

  apply-mac:
    name: Apply (macOS self-hosted)
    runs-on: [self-hosted, mac]
    if: github.event_name == 'workflow_dispatch' && inputs.target == 'mac'
    defaults:
      run:
        shell: bash
        working-directory: infra/envs/dev
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (temporary creds)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init (backend.hcl)
        run: terraform init -input=false -reconfigure -backend-config="backend.hcl"

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        env:
          TF_VAR_db_master_password:  ${{ secrets.TF_VAR_DB_MASTER_PASSWORD }}
          TF_VAR_db_master_username:  ${{ secrets.TF_VAR_DB_MASTER_USERNAME }}
        run: terraform apply -input=false -auto-approve

  plan-pr:
    name: Plan (PR)
    runs-on: [self-hosted, macOS]
    if: github.event_name == 'pull_request'
    defaults:
      run:
        shell: bash
        working-directory: infra/envs/dev
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (temporary creds)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init (backend.hcl)
        run: terraform init -input=false -reconfigure -backend-config="backend.hcl"

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan
