name: Terraform

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "infra/**" ]
  pull_request:
    paths: [ "infra/**" ]

permissions:
  id-token: write
  contents: read

jobs:
  tf:
    runs-on: self-hosted

    defaults:
      run:
        shell: powershell
        working-directory: infra/envs/dev

    concurrency:
      group: terraform-${{ github.ref }}
      cancel-in-progress: true

    env:
      TF_VAR_db_master_username: ${{ secrets.DB_MASTER_USERNAME }}
      TF_VAR_db_master_password: ${{ secrets.DB_MASTER_PASSWORD }}
      TF_VAR_aws_region: eu-central-1

    steps:
      - name: Checkout (clean)
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::760981412376:role/GitHubActionsOIDC
          aws-region: eu-central-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init (met backend.hcl)
        run: terraform init -input=false -reconfigure -backend-config="backend.hcl"

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan (PR)
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply (push main)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false -auto-approve
